# Porta do servidor
server.port=8081

# Configuração da Base de Dados (Ajusta o nome da BD e a senha se necessário)
spring.datasource.url=jdbc:postgresql://localhost:5432/scientific_library
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf (Para veres alterações no HTML sem reiniciar)
spring.thymeleaf.cache=false