# ================================
# CONFIGURAÇÃO DA BASE DE DADOS
# ================================
spring.datasource.url=jdbc:postgresql://localhost:5432/scientific_library
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / HIBERNATE
# ================================

# Valida o mapeamento das entidades sem alterar a BD
spring.jpa.hibernate.ddl-auto=validate


# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs detalhados (útil para debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ================================
# THYMELEAF (opcional)
# ================================
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# ================================
# SERVER (opcional)
# ================================
server.port=8080
