# URL da base de dados (garante que o nome 'library_db' existe no teu Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/scientific_library
spring.datasource.username=postgres
spring.datasource.password=123456

# Driver do Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect